services:
  db: 
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: financial_db
    ports:
      - "5434:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 

  app: 
    build: . 
    ports:
      - "8080:8080" 
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/financial_db?sslmode=disable"
    depends_on:
      - db 

volumes:
  pgdata: 




